"""quant_hybrid.py - int16 quantisation of the Hybrid DPD + C export.

Hybrid:  D(x) = W_mp . phi_MP(x)  +  NN([I,Q,|x|] taps)
  - polynomial branch: linear on the complex MP basis phi (Nc=M*Np terms)
  - neural branch: 3-layer MLP (residual zero-init)
Both quantised to int16 (per-tensor scales) with an integer requant; exports a C
header + reference I/O and reports end-to-end ACLR/EVM loss (float vs int16).
"""
import numpy as np, torch, dsp, pa
from models import HybridDPD, real_features
from train import train_dla, nn_apply, poly_dpd_train

def q(a, s):  return np.clip(np.round(a/s), -32768, 32767).astype(np.int64)
def req(acc, reqk, bq, sh):
    t = acc*reqk + (bq << sh) + (1 << (sh-1)); return t >> sh

def build(x, model, ylin_from, nn_from, G, Np=3, M=4):
    """ylin_from(y_g) -> LS poly inverse ; used to LS-init the polynomial branch."""
    pass

if __name__ == "__main__":
    import os
    M, Np, H, SHIFT = 4, 3, 32, 30
    x_tr = dsp.scale(dsp.gen_ofdm(4096, seed=11), 0.25)
    x_te = dsp.scale(dsp.gen_ofdm(4096, seed=999), 0.25)
    PA = pa.MP_PA(); G = PA.c[0]
    torch.manual_seed(0)
    m = HybridDPD(M, Np, H)
    c = poly_dpd_train(PA(x_tr)/G, x_tr)              # LS prior
    Nc = len(c)
    with torch.no_grad():
        m.lin.weight[0, :Nc] = torch.tensor(c.real); m.lin.weight[0, Nc:] = torch.tensor(-c.imag)
        m.lin.weight[1, :Nc] = torch.tensor(c.imag); m.lin.weight[1, Nc:] = torch.tensor(c.real)
        m.lin.bias.zero_()
    train_dla(m, x_tr, pa.torch_mp_pa(), G, epochs=2000, lr=5e-3)
    torch.save(m.state_dict(), "Hybrid.pt")

    sd = m.state_dict()
    Wl = sd["lin.weight"].numpy().astype(np.float64); bl = sd["lin.bias"].numpy().astype(np.float64)
    W0 = sd["net.0.weight"].numpy().astype(np.float64); b0 = sd["net.0.bias"].numpy().astype(np.float64)
    W2 = sd["net.2.weight"].numpy().astype(np.float64); b2 = sd["net.2.bias"].numpy().astype(np.float64)
    W4 = sd["net.4.weight"].numpy().astype(np.float64); b4 = sd["net.4.bias"].numpy().astype(np.float64)

    def met(x, y):
        lo, up = dsp.aclr_db(y); return min(lo, up), dsp.evm_pct(x, y)

    zf = nn_apply(m, x_te)
    print(f"float Hybrid : ACLR {met(x_te, PA(zf))[0]:7.2f}  EVM {met(x_te, PA(zf))[1]:.4f}%")

    # ---- scales from calibration set ----
    phi_tr = pa.mp_basis(x_tr, M, Np)                  # (N,Nc) complex
    f_tr = np.concatenate([phi_tr.real, phi_tr.imag], axis=1)
    # PEAK-HEADROOM calibration: the fixed-point scale must cover the operating
    # range, not just the calibration set, or unseen peaks clip the basis (and
    # those peaks are where the PA compresses most). 2x headroom below.
    HEADROOM = 2.0
    Sphi = float(np.abs(f_tr).max())*HEADROOM/32700.0
    Sl = float(np.abs(Wl).max())/32767.0
    Slin = Sl*Sphi
    # MLP activations
    fe_tr = real_features(torch.as_tensor(x_tr, dtype=torch.complex64), M).numpy().astype(np.float64)
    a0 = fe_tr
    h1 = np.maximum(a0 @ W0.T + b0, 0); h2 = np.maximum(h1 @ W2.T + b2, 0)
    SX0 = float(np.abs(a0).max())/32700.0
    SX1 = float(np.abs(h1).max())/32700.0
    SX2 = float(np.abs(h2).max())/32700.0
    SW0 = float(np.abs(W0).max())/32767.0; SW2 = float(np.abs(W2).max())/32767.0; SW4 = float(np.abs(W4).max())/32767.0
    REQ0 = int(round(SW0*SX0/SX1*(1 << SHIFT))); BQ0 = np.round(b0/SX1).astype(np.int64)
    REQ1 = int(round(SW2*SX1/SX2*(1 << SHIFT))); BQ1 = np.round(b2/SX2).astype(np.int64)

    def fixed(x):
        phi = pa.mp_basis(x, M, Np)
        f = np.concatenate([phi.real, phi.imag], axis=1)
        fq = q(f, Sphi)
        Wlq = q(Wl, Sl)
        yl = (fq @ Wlq.T)*(Slin) + bl                       # (N,2)
        fe = real_features(torch.as_tensor(x, dtype=torch.complex64), M).numpy().astype(np.float64)
        a0q = q(fe, SX0)
        a1q = np.clip(np.maximum(req(a0q @ q(W0, SW0).T, REQ0, BQ0, SHIFT), 0), -32768, 32767)
        a2q = np.clip(np.maximum(req(a1q @ q(W2, SW2).T, REQ1, BQ1, SHIFT), 0), -32768, 32767)
        yn = (a2q @ q(W4, SW4).T)*(SW4*SX2) + b4
        return (yl[:, 0] + yn[:, 0]) + 1j*(yl[:, 1] + yn[:, 1])

    zq = fixed(x_te); zi = fixed(x_tr)
    zif = nn_apply(m, x_tr)
    cfid = dsp.nmse_db(zif, zi)
    print(f"int16 Hybrid : ACLR {met(x_te, PA(zq))[0]:7.2f}  EVM {met(x_te, PA(zq))[1]:.4f}%")
    print(f"loss         : {met(x_te,PA(zq))[0]-met(x_te,PA(zf))[0]:+.2f} dB ACLR   "
          f"{met(x_te,PA(zq))[1]-met(x_te,PA(zf))[1]:+.4f} pp EVM   (corr fid {-cfid:.1f} dB)")

    # ---- export C header + reference I/O ----
    os.makedirs("deploy", exist_ok=True)
    with open("deploy/hybrid_weights.h", "w") as f:
        f.write("// auto-generated by quant_hybrid.py\n#pragma once\n")
        f.write(f"#define HY_M {M}\n#define HY_NP {Np}\n#define HY_NC {Nc}\n#define HY_IN {3*M}\n#define HY_MID {H}\n#define HY_SHIFT {SHIFT}\n")
        def arr(name, A, t="short"):
            f.write(f"static const {t} {name}[{A.size}] = {{\n")
            fl = A.reshape(-1)
            for i in range(0, fl.size, 12):
                ch = fl[i:i+12]
                vals = (repr(float(v)) for v in ch) if t == "double" else (str(int(v)) for v in ch)
                f.write("  " + ",".join(vals) + ",\n")
            f.write("};\n")
        arr("HY_WL", q(Wl, Sl)); arr("HY_BL", bl, "double")
        arr("HY_W0", q(W0, SW0)); arr("HY_W2", q(W2, SW2)); arr("HY_W4", q(W4, SW4))
        arr("HY_B0", BQ0, "int"); arr("HY_B2", BQ1, "int"); arr("HY_B4", b4, "double")
        for nm, v in (("HY_Sphi", Sphi), ("HY_Sl", Sl), ("HY_SX0", SX0), ("HY_SX1", SX1),
                      ("HY_SX2", SX2), ("HY_SW4", SW4)):
            f.write(f"static const double {nm} = {v!r};\n")
        f.write(f"#define HY_REQ0 {REQ0}\n#define HY_REQ1 {REQ1}\n")
    # reference: N samples input (Q15) + expected output (Q15)
    NP = 32
    xi = np.round(x_te.real*32768).astype(np.int64); xq_ = np.round(x_te.imag*32768).astype(np.int64)
    with open("deploy/hybrid_ref_io.txt", "w") as f:
        for t in range(NP):
            f.write(f"{xi[t]&0xFFFF:04x} {xq_[t]&0xFFFF:04x} "
                    f"{int(np.round(zq[t].real*32768))&0xFFFF:04x} {int(np.round(zq[t].imag*32768))&0xFFFF:04x}\n")
    print("wrote deploy/hybrid_weights.h + hybrid_ref_io.txt")
